// Datos de ejemplo para validar la UI de la Bandeja antes de conectar
// Supabase real (contacts/conversations/messages/conversation_insights).
// Forma alineada a esas tablas para que el cableado real después sea
// mayormente un cambio de fuente de datos, no de estructura.

export const mockConversations = [
  {
    id: 1,
    contacto: "Laura Méndez",
    empresa: "Nortline Logística",
    canal: "chat_web",
    hora: "18:24",
    valor: 14_000_000,
    score: 62,
    sentimiento: "neutro",
    preview: "Quisiera saber cómo automatizan el seguimiento de pedidos...",
    sugerencia: "Preguntó por seguimiento de pedidos. Ofrecele agendar una demo del módulo de tracking.",
    mensajes: [
      { dir: "in", texto: "Hola! Quisiera saber cómo automatizan el seguimiento de pedidos para clientes." },
      { dir: "out", texto: "Hola Laura, con gusto. Usamos un agente que responde el estado del pedido en WhatsApp automáticamente." },
    ],
  },
  {
    id: 2,
    contacto: "Andrés Rico",
    empresa: "Rico & Asociados",
    canal: "chat_web",
    hora: "09:51",
    valor: 18_500_000,
    score: 91,
    sentimiento: "positivo",
    preview: "Perfecto, me interesa avanzar con una propuesta formal...",
    sugerencia: "Ya pidió propuesta formal. Enviale la plantilla de cotización con el paquete de automatización.",
    mensajes: [
      { dir: "in", texto: "Perfecto, me interesa avanzar con una propuesta formal." },
      { dir: "out", texto: "Genial Andrés, te la preparo hoy mismo y te la comparto por acá." },
    ],
  },
  {
    id: 3,
    contacto: "Camila Ortiz",
    empresa: "Cobranzas Pacífico",
    canal: "instagram",
    hora: "ayer",
    valor: 22_000_000,
    score: 85,
    sentimiento: "positivo",
    preview: "¿Tienen algo similar a lo que hicieron para WT...",
    sugerencia: "Preguntó por el caso WTW. Compartile el caso de estudio de cobranzas del portafolio.",
    mensajes: [
      { dir: "in", texto: "Vi su caso de cobranzas en el portafolio, ¿tienen algo similar para nosotros?" },
      { dir: "out", texto: "¡Sí! Es prácticamente el mismo problema. Te cuento cómo lo resolvimos." },
    ],
  },
  {
    id: 4,
    contacto: "Nicolás Fabra",
    empresa: "Fabra Seguros",
    canal: "messenger",
    hora: "11:48",
    valor: 9_000_000,
    score: 47,
    sentimiento: "neutro",
    preview: "¿Cuánto demora la implementación?",
    sugerencia: "Pregunta por tiempos. Compartile el cronograma típico de 3 semanas del Sprint 1.",
    mensajes: [{ dir: "in", texto: "¿Cuánto demora la implementación?" }],
  },
  {
    id: 5,
    contacto: "Sofía Restrepo",
    empresa: "Restrepo Legal",
    canal: "whatsapp",
    hora: "mar",
    valor: 12_000_000,
    score: 58,
    sentimiento: "neutro",
    preview: "Vi tu publicación sobre automatización legal...",
    sugerencia: "Llegó por contenido orgánico. Ofrecele el caso de estudio del bufete jurídico.",
    mensajes: [{ dir: "in", texto: "Vi tu publicación sobre automatización legal, ¿cómo funciona para un bufete?" }],
  },
  {
    id: 6,
    contacto: "Diego Salas",
    empresa: "Salas Construcciones",
    canal: "whatsapp",
    hora: "vie",
    valor: 16_000_000,
    score: 73,
    sentimiento: "positivo",
    preview: "Listo, arrancamos el lunes",
    sugerencia: "Ya confirmó arranque. Coordinale la reunión de kickoff con el equipo técnico.",
    mensajes: [{ dir: "out", texto: "Quedamos entonces para arrancar el lunes, ¿te parece?" }, { dir: "in", texto: "Listo, arrancamos el lunes" }],
  },
];
